2020/12/15 07:22:45 [error] 44#44: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.4, server: kc.kobo.local, request: "GET /service_health/ HTTP/1.1", upstream: "http://172.27.0.5:8001/service_health/", host: "kc.docker.internal"
2020/12/15 07:22:55 [error] 44#44: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.4, server: kc.kobo.local, request: "GET /service_health/ HTTP/1.1", upstream: "http://172.27.0.5:8001/service_health/", host: "kc.docker.internal"
2020/12/15 07:23:05 [error] 44#44: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.4, server: kc.kobo.local, request: "GET /service_health/ HTTP/1.1", upstream: "http://172.27.0.5:8001/service_health/", host: "kc.docker.internal"
2020/12/15 07:23:15 [error] 44#44: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.4, server: kc.kobo.local, request: "GET /service_health/ HTTP/1.1", upstream: "http://172.27.0.5:8001/service_health/", host: "kc.docker.internal"
2020/12/15 07:23:25 [error] 44#44: *37 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.4, server: kc.kobo.local, request: "GET /service_health/ HTTP/1.1", upstream: "http://172.27.0.5:8001/service_health/", host: "kc.docker.internal"
2020/12/15 07:33:32 [error] 43#43: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.5, server: kc.kobo.local, request: "GET /service_health/ HTTP/1.1", upstream: "http://172.29.0.4:8001/service_health/", host: "kc.docker.internal"
2020/12/15 07:33:42 [error] 43#43: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.5, server: kc.kobo.local, request: "GET /service_health/ HTTP/1.1", upstream: "http://172.29.0.4:8001/service_health/", host: "kc.docker.internal"
